export const DIRECTIONS = [
  {
    id:'signal', name:'Signal Bureau',
    title:'Less busywork.<br>More business.',
    description:'Websites, automation and AI agents that turn attention into action.',
    serviceHeading:'Make room for better work.',
    display:'Barlow Condensed', body:'Public Sans',
    tokens:{bg:'#F4F4EC',surface:'#E7E8DD',ink:'#22251F',muted:'#5A5F50',accent:'#D1DE59','accent-ink':'#22251F',line:'#C2C6B6'},
    palette:[['Paper','#F4F4EC'],['Graphite','#22251F'],['Citron','#D1DE59'],['Stone','#E7E8DD'],['Olive gray','#5A5F50']],
    summary:'A crisp, industrial direction with warm paper, condensed typography and precise mechanical forms. Confident and practical without feeling corporate.',
    typeNote:'Barlow Condensed gives the headline a compact, poster-like presence. Public Sans keeps service descriptions approachable and clear.',
    motion:'Graphite rails separate while a citron carrier moves between them. The sculpture suggests information passing through a connected business system.',
    caption:'Warm paper / citron / precision machinery',
    alt:'Graphite rails with a citron carrier on warm paper',
    exposure:1.15,
  },
  {
    id:'nocturne',name:'Nocturne',
    title:'Design with depth.<br>Built for clarity.',
    description:'Distinctive websites and connected systems for businesses ready to move forward.',
    serviceHeading:'A clearer way to grow.',
    display:'Unbounded',body:'Onest',
    tokens:{bg:'#081B26',surface:'#102A37',ink:'#EBF3F2',muted:'#ADC1C9',accent:'#91DDD2','accent-ink':'#081B26',line:'#33515E'},
    palette:[['Midnight','#081B26'],['Pearl','#EBF3F2'],['Aquamarine','#91DDD2'],['Deep blue','#102A37'],['Mist','#ADC1C9']],
    summary:'A cinematic midnight palette with architectural glass and a wide, modern typeface. The sculpture leads on the left; the offer stays clear on the right.',
    typeNote:'Unbounded creates a distinctive geometric headline. Onest brings a softer, highly readable voice to navigation and supporting copy.',
    motion:'Seven glass fins open into a fan, with subtle pointer tilt and shifting studio reflections. Layering gives the hero depth without a noisy background.',
    caption:'Midnight / aquamarine / architectural glass',
    alt:'Seven architectural aquamarine glass fins against midnight navy',
    exposure:1.05,
  },
  {
    id:'garnet',name:'Garnet House',
    title:'Beautifully built.<br>Brilliantly useful.',
    description:'Expressive websites and intelligent systems, made to serve your business.',
    serviceHeading:'Craft meets capability.',
    display:'Cormorant Garamond',body:'Karla',
    tokens:{bg:'#3A1727',surface:'#492335',ink:'#F5EDE8',muted:'#D8BFC7',accent:'#D5A6B4','accent-ink':'#3A1727',line:'#805768'},
    palette:[['Garnet','#3A1727'],['Porcelain','#F5EDE8'],['Rose','#D5A6B4'],['Wine','#492335'],['Dusty blush','#D8BFC7']],
    summary:'An editorial identity influenced by couture materials and sculptural folds. Rich burgundy, soft rose and expressive serif type give the studio a distinctive creative presence.',
    typeNote:'Cormorant Garamond adds a fashion-editorial character. Karla keeps the service copy direct and prevents the visual language from becoming ornate.',
    motion:'A continuous satin-like ribbon turns slowly, revealing its folded surface. The alternating service layout echoes the rhythm of the fold.',
    caption:'Burgundy / rose / folded satin',
    alt:'A sculptural rose satin ribbon with garnet folds',
    exposure:1.15,
  },
  {
    id:'ember',name:'Ember Studio',
    title:'Good looks.<br>Serious systems.',
    description:'Websites that earn attention. Automation and AI that make the work easier.',
    serviceHeading:'Built to work together.',
    display:'Urbanist',body:'Work Sans',
    tokens:{bg:'#1B1B18',surface:'#2C2B27',ink:'#F2ECE4',muted:'#BBB6AC',accent:'#E9AF88','accent-ink':'#1B1B18',line:'#5A564E'},
    palette:[['Soot','#1B1B18'],['Chalk','#F2ECE4'],['Copper','#E9AF88'],['Smoke','#2C2B27'],['Warm gray','#BBB6AC']],
    summary:'Warm industrial luxury, with a centered headline and a wide copper sculpture. Rounded typography gives the studio confidence without the coldness of a typical dark tech site.',
    typeNote:'Urbanist provides an open, contemporary display face. Work Sans gives longer copy a steady, practical rhythm.',
    motion:'Two copper links interlock and turn as a single assembly. Warm reflections reinforce the idea of websites, automation and AI working together.',
    caption:'Charcoal / copper / linked metal',
    alt:'Two burnished copper links on warm charcoal',
    exposure:1.1,
  },
];
